### ISSUE TITLE
Fix size of image as profile picture for the website

### ISSUE THREAD

**Issue by paniash** [paniash/website#4]
Currently, I've not been able to come across a solution for inserting a profile picture on `index.md` wrapped with text. Using some google-fu,

```
~~~
<img align="right" src="assets/images/my-passport-photo.jpg">
~~~
```

Works for the wrapping part but doesn't help scale the image to a size appropriate for a profile picture. Tried including `width="200px"` in the above snippet but changing the values of `width` doesn't affect the picture at all. Rather it disproportionately alters the aspect ratio of the image.

Could you help me out? @tlienart

**Comment by tlienart** [comment]
Can you try something like this:

```
@@myprofile
![me](path)
@@
```

then in the CSS

```
.myprofile img {
  align: right;
  width: 200px;
}
```

if that doesn't work, have a look at your browser dev tools to see what's going on with the element; I'm away from a computer so can't try this myself but could tomorrow if you're still stuck

**Comment by paniash** [comment]
Ok, so I did as you suggested but it didn't work. Upon inspecting the browser dev tools, I found out that the above css line is not used but instead the below snippet is:

```css
.franklin-content img {
  width: 70%;
  text-align: center;
  padding-left: 10%;
}
```

**Comment by paniash** [comment]
Ok, so while investigating, I found out that doing the following **without** the `img` option, seems to work:

```css
.displayPicture {
    width: 40%;
    float: right;
    padding-left: 1%;
    padding-right: 0%;
    padding-bottom: 1%;
    padding-top: 5%;
}
```

with `index.md` containing:

```
@@displayPicture
![me](assets/images/my-passport-photo.jpg)
@@
```
